//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppVetclinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public int stuffID { get; set; }
        public int userID { get; set; }
        public int orderProductsID { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal orderCost { get; set; }
    
        public virtual orderProducts orderProducts { get; set; }
        public virtual Stuffs Stuffs { get; set; }
        public virtual Users Users { get; set; }
    }
}
